#!/bin/bash
#convert +append ../render02000.png ../withSurf/render02000.png ../noSurf/render02000.png oute.png

for i in {0..9}
do
   echo $i
   convert +append ../render0000$i.png ../withSurf/render0000$i.png ../noSurf/render0000$i.png render0000$i.png
done

for i in {10..99}
do
   echo $i
   convert +append ../render000$i.png ../withSurf/render000$i.png ../noSurf/render000$i.png render000$i.png
done

for i in {100..999}
do
   echo $i
   convert +append ../render00$i.png ../withSurf/render00$i.png ../noSurf/render00$i.png render00$i.png
done

for i in {1000..2000}
do
   echo $i
   convert +append ../render0$i.png ../withSurf/render0$i.png ../noSurf/render0$i.png render0$i.png
done
